version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/sample-springboot-api

    steps:
      # git pull
      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - sample-springboot-api-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sample-springboot-api-{{ checksum "pom.xml" }}

      # package into a jar
      - run: mvn clean test

